let list = JSON.parse(`{
    "Javascript": {"name": "Javascript", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "React": {"name": "React", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Angular": {"name": "Angular", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "CSS": {"name": "CSS", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Node.js": {"name": "Node.js", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "PHP": {"name": "PHP", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Vue": {"name": "Vue", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Django": {"name": "Django", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Machine Learning": {"name": "Machine Learning", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Python": {"name": "Python", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Deep Learning": {"name": "Deep Learning", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Data Analysis": {"name": "Data Analysis", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Artificial Intelligence": {"name": "Artificial Intelligence", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "TensorFlow": {"name": "Tensorflow", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "R": {"name": "R", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Neural Networks": {"name": "Neural Networks", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Android Development": {"name": "Android Development", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "iOS Development": {"name": "iOS Development", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Google Flutter": {"name": "Google Flutter", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Swift": {"name": "Swift", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "React Native": {"name": "React Native", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Dart Programming Language": {"name": "Dart Programming Language", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Mobile Development": {"name": "Mobile development", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Ionic": {"name": "Ionic", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Kotlin": {"name": "Kotlin", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Python": {"name": "Python", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Java": {"name": "Java", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "C#": {"name": "C#", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "React": {"name": "React", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "C++": {"name": "C++", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Javascript": {"name": "Javascript", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Spring Framework": {"name": "Spring Framework", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Object-Oriented Programming": {"name": "Object-Oriented Programming", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "C": {"name": "C", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Unity": {"name": "Unity", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Game Development Fundamentals": {"name": "Game Development Fundamentals", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "C#": {"name": "C#", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Unreal Engine": {"name": "Unreal Engine", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "3D Game Development": {"name": "3D Game Development", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "C++": {"name": "C++", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "2D Game Development": {"name": "2D Game Development", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Unreal Engine Blueprints": {"name": "Unreal Engine Blueprints", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Mobile Game Developemnt": {"name": "Mobile Game Development", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "SQL": {"name": "SQL", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "MySQL": {"name": "MySQL", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Oracle SQL": {"name": "Oracle SQL", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "MongoDB": {"name": "MongoDB", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Database Management": {"name": "Database Management", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Oracle Certification": {"name": "Oracle Certification", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Apache Kafka": {"name": "Apache Kafka", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Oracle Database": {"name": "Oracle Database", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Selenium WebDriver": {"name": "Selenium WebDriver", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Java": {"name": "Java", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Selenium Testing Network": {"name": "Selenium Testing Network", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Cypress.io": {"name": "Cypress.io", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "API Testing": {"name": "API Testing", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Python": {"name": "Python", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Automation Testing": {"name": "Automation Testing", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Appium": {"name": "Appium", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "AWS Certification": {"name": "AWS Certification", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "AWS Certified Developer": {"name": "AWS Certified Developer - Associate", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Interviewing Skills": {"name": "Interviewing Skills", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Professional Scrum Master (PSM)": {"name": "Professional Scrum Master (PSM)", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Agile": {"name": "Agile", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Kubernetes": {"name": "Kubernetes", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Python": {"name": "Python", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Microservices": {"name": "Microservices", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Big Data": {"name": "Big Data", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Docker": {"name": "Docker", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Kubernetes": {"name": "Kubernetes", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Git": {"name": "Git", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "DevOps": {"name": "DevOps", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Jenkins": {"name": "Jenkins", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "JIRA": {"name": "JIRA", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "AWS Certification": {"name": "AWS Certification", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "AWS Certified Developer": {"name": "AWS Certified Developer", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Confluence": {"name": "Confluence", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "WooCommerce": {"name": "WooCommerce", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Shopify": {"name": "Shopify", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Magento": {"name": "Magento", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Wordpress for Ecommerce": {"name": "Wordpress for Ecommerce", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Wordpress": {"name": "Wordpress", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "PrestaShop": {"name": "PrestaShop", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Web Development": {"name": "Web Development", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."},
    "Online Business": {"name": "Online Business", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, reiciendis iste in repudiandae, enim iure nobis odit molestiae id, aperiam voluptatum tempore ex quod sunt aspernatur accusamus rem maiores alias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur harum, labore laudantium illo, porro quo, delectus repellat accusantium sed autem facere accusamus quidem eveniet quod? Quod, sit temporibus? Ullam, iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci omnis nostrum enim culpa non, assumenda, quo soluta dolorum ratione animi odit earum saepe deserunt tempore iure accusamus, natus id. Numquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, sequi dolores voluptates voluptatum quod ex eum ut magnam praesentium error. Nulla, incidunt veritatis. Ab recusandae consequuntur eum, dolor dicta non."}
}`)

let filteredList = document.querySelector('.search-bar__field');
let paragraph = document.querySelectorAll('.gallery-item__para');
let emptyList = document.querySelector('#list-svuota');
let changeView = document.querySelectorAll('.list__options__radio');
let grid = document.querySelector('.gallery-grid');
let gridItem = document.querySelectorAll('.gallery-item');
let gridPic = document.querySelectorAll('.gallery-item__pic');
let gridText = document.querySelectorAll('.gallery-item__para');

changeView[0].addEventListener('click', function (e) {
    turnToGrid(e);
});
changeView[1].addEventListener('click', function (e) {
    turnToList(e);
});

emptyList.addEventListener('click', function (e) {
    emptyOrFill(e);
});


filteredList.addEventListener('input', function (e) {
    filterList(e);
});

let emptyOrFill = function (e) {
    for (let item of paragraph) {
        if (e.target.checked) {
            item.parentElement.style.display = 'none';
        } else {
            item.parentElement.style.display = 'flex';
        }
    }
}

let filterList = function (listItem) {
    for (let item of paragraph) {
        if (!item.textContent.toLowerCase().includes(listItem.target.value.toLowerCase())) {
            item.parentElement.style.display = 'none';
        } else {
            item.parentElement.style.display = 'flex';
        }
    }
}

let turnToGrid = function (e) {
    for(let i = 0; i < gridItem.length; i++) {
        if(grid.classList.contains('gallery-grid--list')) {
            grid.classList.remove('gallery-grid--list');
        }
    }
    e.target.checked = true;

    grid.style.gridTemplateColumns = 'repeat(auto-fit, minmax(300px, 1fr))';
    grid.style.gridTemplateRows = '1fr';
    for(let i = 0; i < gridItem.length; i++) {
        gridItem[i].style.gridColumn = 'span 1';
        gridPic[i].style.display = 'flex';
        gridItem[i].style.flexDirection = 'column';
        gridPic[i].style.width = '100%';    
        gridText[i].style.width = '100%';
        gridText[i].style.margin = '1.5rem 0';
    }
    if (window.innerWidth < '650') {
        grid.style.gridTemplateColumns = 'repeat(auto-fit, minmax(300px, 1fr))';
        grid.style.gridTemplateRows = '1fr';
    }
}

let turnToList = function (e) {
    grid.classList.add('gallery-grid--list');
    e.target.checked = true;

    grid.style.gridTemplateColumns = '1fr';
    grid.style.gridTemplateRows = 'auto';
    grid.style.gridGap = '';
    
    for (let i = 0; i < gridItem.length; i++) {
        gridItem[i].style.flexDirection = 'row';
        gridItem[i].style.gridColumn = '1 / -1';
        gridItem[i].style.width = '100%';
        gridPic[i].style.width = '50%';
        gridText[i].style.width = '50%';
        gridItem[i].style.justifyContent = 'center';
    }
    if (window.innerWidth < '650') {
        for(let i = 0; i < gridItem.length; i++) {
            gridPic[i].style.display = 'flex';
            gridPic[i].style.display = 'none';
            gridText[i].style.width = '100%';
            // grid.style.gridTemplateRows = '6rem';
        }
    }
}